/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseInput: typeof import('./components/ui/BaseInput.vue')['default']
    BaseSelect: typeof import('./components/ui/BaseSelect.vue')['default']
    BaseVSelect: typeof import('./components/ui/BaseVSelect.vue')['default']
    CourseCard: typeof import('./components/CourseCard.vue')['default']
    CourseModal: typeof import('./components/CourseModal.vue')['default']
    CreateCourseModal: typeof import('./components/CreateCourseModal.vue')['default']
    CreateLessonModal: typeof import('./components/CreateLessonModal.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    LessonCard: typeof import('./components/LessonCard.vue')['default']
    LessonModal: typeof import('./components/LessonModal.vue')['default']
    LoginLayout: typeof import('./components/layouts/LoginLayout.vue')['default']
    Logo: typeof import('./components/ui/Logo.vue')['default']
    MainLayout: typeof import('./components/layouts/MainLayout.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCourses: typeof import('./components/Index/SearchCourses.vue')['default']
    Teachers: typeof import('./components/Index/Teachers.vue')['default']
  }
}
